<Screem>:
    orientation: 'rl-bt'
    Button:
        text: 'A'
        size_hint: .4, .1
    Button:
        text: 'B'
        size_hint: .4, .1
    Button:
        text: 'C'
        size_hint: .4, .1
    Button:
        text: 'D'
        size_hint: .4, .1
    Button:
        text: 'E'
        size_hint: .4, .1
    Button:
        text: 'F'
        size_hint: .4, .1
    Button:
        text: 'G'
        size_hint: .4, .1